"""
pages/8_Reports.py — Client-grade PDF + Data exports.
Integrates stats, BI, ML, charts into one narrative report.
"""
import streamlit as st
import pandas as pd
import numpy as np
import io

from core.session_manager import (
    require_data, get_df, get_filename, get_file_size,
    get_cached_stats, get_cached_story, get_cached_ml,
)

st.set_page_config(page_title="Reports", layout="wide")
require_data()

df     = get_df()
fname  = get_filename()

from core.pdf_builder import build_pdf, THEMES
from core.chart_exporter import generate_all_charts
from core.story_engine import generate_story
from core.data_profiler import profile_dataset

COLORS = ["#1a4a8a", "#2196F3", "#22d3a5", "#f7934f", "#a78bfa", "#f77070"]

st.markdown("## Reports & Export")
st.caption("{} — {:,} rows, {} columns".format(fname, len(df), len(df.columns)))
st.divider()

# ══════════════════════════════════════════════════════════
#  SECTION 1 — REPORT CONFIG
# ══════════════════════════════════════════════════════════
st.markdown("### Report Configuration")

c1, c2, c3 = st.columns(3)
with c1:
    report_title  = st.text_input("Report Title",
                                  value="Data Analysis Report — {}".format(fname))
    client_name   = st.text_input("Client / Prepared For", value="Client")
with c2:
    theme_name    = st.selectbox("Theme", list(THEMES.keys()), index=0)
    subtitle      = st.text_input("Subtitle (optional)",
                                  value="Powered by DataForge AI")
with c3:
    confidential  = st.toggle("Confidential stamp", value=True)
    st.markdown("<br>", unsafe_allow_html=True)
    include_stats = st.toggle("Include Statistical Analysis", value=True)
    include_bi    = st.toggle("Include Business Intelligence", value=True)
    include_ml    = st.toggle("Include ML Results", value=False,
                              help="Only if ML was run on this dataset")

st.divider()

# ══════════════════════════════════════════════════════════
#  SECTION 2 — WHAT'S INCLUDED
# ══════════════════════════════════════════════════════════
st.markdown("### Report Contents")
c1, c2, c3, c4 = st.columns(4)

stats_cached = get_cached_stats()
story_cached = get_cached_story()
ml_cached    = get_cached_ml()

c1.metric("Cover + TOC",         "Included")
c2.metric("Executive Summary",   "AI Generated")
c3.metric("Dataset Overview",    "Included")
c4.metric("Data Cleaning Log",   "Included")

c5, c6, c7, c8 = st.columns(4)
c5.metric("Statistical Analysis",
          "Included" if stats_cached and include_stats else "Not cached")
c6.metric("Business Intelligence",
          "Included" if include_bi else "Skipped")
c7.metric("ML Predictions",
          "Included" if ml_cached and include_ml else "Skipped")
c8.metric("Charts (auto)", "Up to 5")

if stats_cached is None and include_stats:
    st.info(
        "Statistical analysis not cached. "
        "Visit Data Quality page first for full stats in report.")

if ml_cached is None and include_ml:
    st.info(
        "ML results not cached. "
        "Visit ML Predictions page and train models first.")

st.divider()

# ══════════════════════════════════════════════════════════
#  SECTION 3 — GENERATE PDF
# ══════════════════════════════════════════════════════════
st.markdown("### Generate PDF Report")

col_btn, col_info = st.columns([1, 3])
with col_btn:
    gen_btn = st.button("Generate PDF Report",
                        type="primary", use_container_width=True)
with col_info:
    st.caption(
        "Generates a complete multi-page PDF with narrative insights, "
        "charts, statistical analysis, and actionable recommendations."
    )

if gen_btn:
    with st.spinner("Building report... this may take 20-40 seconds."):

        # ── Profile ───────────────────────────────────────
        try:
            profile = profile_dataset(df)
        except Exception:
            profile = None

        # ── Cleaning summary from session ─────────────────
        cleaning_summary = st.session_state.get("clean_report")

        # ── Story / Business insights ─────────────────────
        try:
            story = generate_story(df)
            exec_summary  = story.executive_summary
            findings      = story.key_findings
            risks         = story.business_risks
            opportunities = story.opportunities
            actions       = story.recommended_actions
        except Exception:
            exec_summary  = "Analysis generated by DataForge AI."
            findings = risks = opportunities = actions = []

        # ── Stats ─────────────────────────────────────────
        stats_report = stats_cached if include_stats else None

        # ── BI ────────────────────────────────────────────
        bi_report = None
        if include_bi:
            try:
                from core.bi_engine import run_bi
                bi_report = run_bi(df)
            except Exception:
                pass

        # ── ML ────────────────────────────────────────────
        ml_report = ml_cached if include_ml else None

        # ── Charts ────────────────────────────────────────
        chart_data = []
        try:
            charts = generate_all_charts(df, theme_name, max_charts=5)
            for title, img_bytes in charts:
                if img_bytes:
                    # Simple narrative per chart
                    narrative = _chart_narrative(df, title)
                    chart_data.append((title, img_bytes, narrative))
        except Exception:
            pass

        # ── Config ────────────────────────────────────────
        config = {
            "title":       report_title,
            "subtitle":    subtitle,
            "client_name": client_name,
            "confidential": confidential,
            "theme_name":  theme_name,
        }

        # ── Build PDF ─────────────────────────────────────
        try:
            pdf_bytes = build_pdf(
                df=df,
                config=config,
                profile=profile,
                cleaning_summary=cleaning_summary,
                stats_report=stats_report,
                bi_report=bi_report,
                ml_report=ml_report,
                chart_data=chart_data,
                executive_summary=exec_summary,
                findings=findings,
                risks=risks,
                opportunities=opportunities,
                recommendations=actions,
            )

            st.success(
                "PDF generated — {:.1f} MB | {} pages (approx.)".format(
                    len(pdf_bytes) / (1024*1024),
                    3 + len(chart_data) +
                    (1 if stats_report else 0) +
                    (1 if bi_report else 0) +
                    (1 if ml_report else 0) + 2
                )
            )

            clean_fname = fname.replace(".csv","").replace(".xlsx","")
            st.download_button(
                label="Download PDF Report",
                data=pdf_bytes,
                file_name="DataForge_Report_{}.pdf".format(clean_fname),
                mime="application/pdf",
                type="primary",
                use_container_width=True,
            )

        except Exception as e:
            st.error("PDF generation failed: {}".format(str(e)))
            st.exception(e)

st.divider()

# ══════════════════════════════════════════════════════════
#  SECTION 4 — DATA EXPORTS
# ══════════════════════════════════════════════════════════
st.markdown("### Data Exports")

c1, c2, c3 = st.columns(3)

# CSV
with c1:
    st.markdown("**Cleaned Data — CSV**")
    st.caption("{:,} rows × {} columns".format(len(df), len(df.columns)))
    csv = df.to_csv(index=False).encode("utf-8")
    st.download_button(
        "Download CSV",
        data=csv,
        file_name="cleaned_{}.csv".format(
            fname.replace(".csv","").replace(".xlsx","")),
        mime="text/csv",
        use_container_width=True,
    )

# Excel
with c2:
    st.markdown("**Cleaned Data — Excel**")
    st.caption("Data + Stats + Quality sheets")
    try:
        buf_xl = io.BytesIO()
        with pd.ExcelWriter(buf_xl, engine="xlsxwriter") as writer:
            df.to_excel(writer, sheet_name="Cleaned Data", index=False)
            # Stats sheet
            desc = df.describe().round(4)
            desc.reset_index().to_excel(
                writer, sheet_name="Statistics", index=False)
            # Column info
            info_rows = []
            for col in df.columns:
                s = df[col]
                info_rows.append({
                    "Column": col,
                    "Type": str(s.dtype),
                    "Missing": int(s.isna().sum()),
                    "Missing %": round(s.isna().mean()*100, 2),
                    "Unique": int(s.nunique()),
                })
            pd.DataFrame(info_rows).to_excel(
                writer, sheet_name="Column Info", index=False)
        buf_xl.seek(0)
        st.download_button(
            "Download Excel",
            data=buf_xl,
            file_name="cleaned_{}.xlsx".format(
                fname.replace(".csv","").replace(".xlsx","")),
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            use_container_width=True,
        )
    except Exception as e:
        st.error("Excel export failed: {}".format(str(e)))

# JSON
with c3:
    st.markdown("**Cleaned Data — JSON**")
    st.caption("Records format — for API / downstream use")
    json_data = df.to_json(orient="records", indent=2)
    st.download_button(
        "Download JSON",
        data=json_data.encode("utf-8"),
        file_name="cleaned_{}.json".format(
            fname.replace(".csv","").replace(".xlsx","")),
        mime="application/json",
        use_container_width=True,
    )


# ── Helper ────────────────────────────────────────────────
def _chart_narrative(df: pd.DataFrame, title: str) -> str:
    """Simple chart narrative without LLM — rule based."""
    num_cols = df.select_dtypes(include="number").columns.tolist()
    cat_cols = df.select_dtypes(include="object").columns.tolist()

    if "Distribution" in title and num_cols:
        col = next((c for c in num_cols if c in title), num_cols[0])
        s   = df[col].dropna()
        return (
            "Distribution of '{}': mean={:.2f}, median={:.2f}, "
            "std={:.2f}. Skewness={:.2f} ({}).".format(
                col, s.mean(), s.median(), s.std(),
                s.skew(),
                "right-skewed" if s.skew()>0.5 else
                "left-skewed" if s.skew()<-0.5 else "symmetric"
            )
        )
    elif "Correlation" in title and num_cols:
        corr = df[num_cols[:5]].corr()
        strongest = corr.abs().unstack().drop_duplicates().sort_values(ascending=False)
        strongest = [(i,j,v) for (i,j),v in strongest.items() if i!=j]
        if strongest:
            a, b, r = strongest[0]
            return (
                "Correlation matrix for {} numeric columns. "
                "Strongest correlation: '{}' and '{}' (r={:.2f}).".format(
                    len(num_cols[:5]), a, b, r)
            )
    elif "by" in title.lower() and cat_cols and num_cols:
        return (
            "Comparison chart showing how the metric varies across categories. "
            "Higher bars indicate segments with above-average performance."
        )
    return "Chart generated from dataset analysis."

